BEGIN TRANSACTION;
DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`USERNAME`	TEXT NOT NULL,
	`PASSWORD`	TEXT NOT NULL,
	`JOIN_DATE`	INTEGER NOT NULL,
	`BIO`	TEXT,
	`ADMIN`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `REVIEW`;
CREATE TABLE IF NOT EXISTS `REVIEW` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`USER_ID`	INTEGER NOT NULL,
	`RESTAURANT_ID`	INTEGER,
	`TIME`	INTEGER NOT NULL,
	`RATING`	INTEGER NOT NULL,
	`BODY`	TEXT NOT NULL,
	FOREIGN KEY(`USER_ID`) REFERENCES `USER`(`ID`)
);
DROP TABLE IF EXISTS `RESTAURANT`;
CREATE TABLE IF NOT EXISTS `RESTAURANT` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`VISIBLE`	INTEGER NOT NULL,
	`NAME`	TEXT NOT NULL,
	`ADDRESS`	TEXT NOT NULL,
	`CATEGORY`	TEXT,
	`WEBSITE`	TEXT
);
DROP TABLE IF EXISTS `REPORT`;
CREATE TABLE IF NOT EXISTS `REPORT` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`REPORTING_USER`	INTEGER NOT NULL,
	`REVIEW_ID`	INTEGER NOT NULL,
	`TIME`	INTEGER NOT NULL,
	`MESSAGE`	TEXT NOT NULL,
	FOREIGN KEY(`REPORTING_USER`) REFERENCES `USER`(`ID`),
	FOREIGN KEY(`REPORTED_USER`) REFERENCES `USER`(`ID`),
	FOREIGN KEY(`REVIEW_ID`) REFERENCES `REVIEW`(`ID`)
);
COMMIT;
